included:
  - ThesisAccessibilityHelper
excluded:
  - ${PWD}/Pods

deployment_target:
  iOS_deployment_target: 16.4

disabled_rules:
  - orphaned_doc_comment

opt_in_rules:
  - indentation_width
  - force_unwrapping
  - redundant_type_annotation
  - force_try
  - operator_usage_whitespace

force_cast: warning

indentation_width:
  indentation_width: 4

line_length:
  warning: 170
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

identifier_name:
  excluded:
    - i
    - id
    - en
